apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: argocd-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: argocd-operator.v0.0.14