apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    solvers:
      - dns01:
          clouddns:
            project: my-gcp-project
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
