apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - acme-issuer.yaml

# This example uses Google's Cloud DNS
# https://cert-manager.io/docs/configuration/acme/dns01/google/
secretGenerator:
  - name: clouddns-dns01-solver-svc-acct
    namespace: cert-manager
    files:
      - key.json

generatorOptions:
  disableNameSuffixHash: true
